### PR TITLE
 update post example to use requests 

### PR DESCRIPTION
**Pull request by jerryneedell**
update post example to use requests - add display.print to countview example

### CODE REVIEW

**Comment by jerryneedell** [comment]
@ladyada  Travis failed for some pre-existing lint issues --  was it OK to make this pull request to your repo? you can kill it if you want and I'll add it after you merge to Adafruit master. I thought it would save a step to update them here.

**Comment by ladyada** [comment]
i was going to merge my current work into here, you can then re-open a PR?

**Comment by jerryneedell** [comment]
OK - no problem

**Comment by jerryneedell** [comment]
will reopen after merge

**Pull request closed without merging**
